name: Build & Deploy RSS feed

on:
  push:
    branches: [ main ]         # change if your default branch is different
  workflow_dispatch:

# These permissions are required for Pages
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Required for GitHub Pages deployments
      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Build feed (verbose)
        run: |
          set -euxo pipefail
          node -v
          node scripts/build-feed.mjs
          # ensure dist exists and has feed
          test -f dist/feed.xml
          # prevent Jekyll munging anything in dist/
          touch dist/.nojekyll
          echo "== head of dist/feed.xml =="
          head -n 40 dist/feed.xml

      - name: Upload artifact for Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
