name: Debug RSS build (no deploy)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show repo tree
        run: |
          echo "== repo tree (root) =="
          ls -la
          echo "== scripts =="
          ls -la scripts || true
          echo "== package.json =="
          cat package.json || true

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Build feed (verbose)
        run: |
          set -euxo pipefail
          node -v
          # Run your script directly (avoids npm script surprises)
          node scripts/build-feed.mjs
          echo "== dist listing =="
          ls -la dist || true
          echo "== head of dist/feed.xml (or diagnostic) =="
          head -n 80 dist/feed.xml || true

      - name: Upload dist artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
