name: Build & Deploy RSS feed

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

env:
  # Adjust if you changed the script
  FEED_PATH: dist/feed.xml
  SOURCE_FEED_URL: http://www.cabletv.com/blog/feed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show repo tree
        run: |
          echo "== repo tree =="
          ls -la
          echo "== scripts/ =="
          ls -la scripts || true
          echo "== package.json =="
          cat package.json || true

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Sanity check source feed
        run: |
          echo "== HEAD of $SOURCE_FEED_URL =="
          curl -fsSL "$SOURCE_FEED_URL" | head -n 40 || true

      - name: Build sanitized feed (verbose)
        run: |
          set -euxo pipefail
          node -v
          # Prefer running the script directly; if you later keep the npm script, either works.
          node scripts/build-feed.mjs
          echo "== head of output =="
          head -n 40 "$FEED_PATH"
          echo "== grep for snf or smartnews =="
          (grep -nE 'xmlns:snf|<snf:|smartnews\.be' "$FEED_PATH" && exit 2) || true
          test -f "$FEED_PATH"

      - name: Upload artifact for Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
