name: Fetch and Clean RSS Feed

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: |
          pip install lxml requests beautifulsoup4
      
      - name: Fetch and Clean RSS Feed
        run: |
          python3 << 'EOF'
          import requests
          from lxml import etree
          from bs4 import BeautifulSoup
          from datetime import datetime, timezone
          import re
          from urllib.parse import quote

          # Fetch the original feed
          print("Fetching original feed...")
          response = requests.get('https://www.cabletv.com/feed')
          print(f"Fetched {len(response.content)} bytes")
          
          # Parse the XML
          root = etree.fromstring(response.content)
          channel = root.find('channel')
          
          # Get all items and limit to 8
          items = channel.findall('item')[:8]
          print(f"Processing {len(items)} items")
          
          # Define namespace map
          nsmap = {
              'content': 'http://purl.org/rss/1.0/modules/content/',
              'wfw': 'http://wellformedweb.org/CommentAPI/',
              'dc': 'http://purl.org/dc/elements/1.1/',
              'atom': 'http://www.w3.org/2005/Atom',
              'sy': 'http://purl.org/rss/1.0/modules/syndication/',
              'slash': 'http://purl.org/rss/1.0/modules/slash/',
              'media': 'http://search.yahoo.com/mrss/',
              'snf': 'http://www.smartnews.be/snf'
          }
          
          # Register all namespaces
          for prefix, uri in nsmap.items():
              etree.register_namespace(prefix, uri)
          
          # Fallback thumbnail for items without images
          fallback_thumbnail = 'https://ctv-clearlink.github.io/RSS-Feed/CableTV.com%20RSS%20Logo%20Header.png'
          
          # Build the XML as a string manually
          xml_parts = []
          xml_parts.append('<?xml version="1.0" encoding="UTF-8"?>')
          xml_parts.append('<rss version="2.0"')
          xml_parts.append(' xmlns:content="http://purl.org/rss/1.0/modules/content/"')
          xml_parts.append(' xmlns:wfw="http://wellformedweb.org/CommentAPI/"')
          xml_parts.append(' xmlns:dc="http://purl.org/dc/elements/1.1/"')
          xml_parts.append(' xmlns:atom="http://www.w3.org/2005/Atom"')
          xml_parts.append(' xmlns:sy="http://purl.org/rss/1.0/modules/syndication/"')
          xml_parts.append(' xmlns:slash="http://purl.org/rss/1.0/modules/slash/"')
          xml_parts.append(' xmlns:media="http://search.yahoo.com/mrss/"')
          xml_parts.append(' xmlns:snf="http://www.smartnews.be/snf">')
          xml_parts.append('<channel>')
          
          # Add channel metadata
          for elem in channel:
              if elem.tag == 'item':
                  break
              tag = elem.tag
              if 'logo' in tag.lower():
                  continue
              
              elem_str = etree.tostring(elem, encoding='unicode', method='xml')
              xml_parts.append(elem_str)
              
              # Add logo after description
              if elem.tag == 'description':
                  logo_filename = 'CableTV.com RSS Logo Header.png'
                  logo_url = f'https://ctv-clearlink.github.io/RSS-Feed/{quote(logo_filename)}'
                  xml_parts.append(f'<snf:logo><url>{logo_url}</url></snf:logo>')
                  print("✓ Added logo")
          
          # Process each item
          cdata_count = 0
          thumbnail_count = 0
          fallback_count = 0
          
          for idx, item in enumerate(items):
              title_elem = item.find('title')
              title_text = title_elem.text if title_elem is not None else 'Unknown'
              print(f"\n--- Item {idx + 1}: {title_text[:50]} ---")
              
              xml_parts.append('<item>')
              
              # Store content_html separately before processing
              content_html = None
              original_content = None
              
              # First pass - find content:encoded
              for elem in item:
                  tag_name = etree.QName(elem.tag).localname if '}' in elem.tag else elem.tag
                  namespace = etree.QName(elem.tag).namespace if '}' in elem.tag else None
                  
                  if namespace == 'http://purl.org/rss/1.0/modules/content/' and tag_name == 'encoded':
                      original_content = elem.text or ''
              
              # Second pass - process and add elements
              for elem in item:
                  tag_name = etree.QName(elem.tag).localname if '}' in elem.tag else elem.tag
                  namespace = etree.QName(elem.tag).namespace if '}' in elem.tag else None
                  
                  # Skip existing media:thumbnail
                  if namespace == 'http://search.yahoo.com/mrss/' and tag_name == 'thumbnail':
                      continue
                  
                  # Handle content:encoded with CDATA
                  if namespace == 'http://purl.org/rss/1.0/modules/content/' and tag_name == 'encoded':
                      if original_content:
                          # Clean up links
                          soup = BeautifulSoup(original_content, 'html.parser')
                          links = soup.find_all('a')
                          if len(links) > 3:
                              for link in links[3:]:
                                  link.unwrap()
                          content_html = str(soup)
                          
                          # Add with CDATA
                          xml_parts.append(f'<content:encoded><![CDATA[{content_html}]]></content:encoded>')
                          cdata_count += 1
                  else:
                      # Serialize other elements normally
                      elem_str = etree.tostring(elem, encoding='unicode', method='xml')
                      xml_parts.append(elem_str)
              
              # NOW extract thumbnail from the original content
              img_url = None
              
              if original_content:
                  # Parse original HTML
                  soup = BeautifulSoup(original_content, 'html.parser')
                  
                  # Find ALL img tags
                  all_imgs = soup.find_all('img')
                  
                  if all_imgs:
                      # Get first image
                      first_img = all_imgs[0]
                      img_url = first_img.get('src') or first_img.get('data-src')
                      
                      if img_url:
                          # Clean and normalize
                          img_url = img_url.strip()
                          
                          # Make absolute URL
                          if img_url.startswith('//'):
                              img_url = 'https:' + img_url
                          elif img_url.startswith('/'):
                              img_url = 'https://www.cabletv.com' + img_url
                          elif not img_url.startswith('http'):
                              img_url = 'https://www.cabletv.com/' + img_url
                          
                          # Escape XML
                          img_url = img_url.replace('&', '&amp;')
                          
                          xml_parts.append(f'<media:thumbnail url="{img_url}"/>')
                          thumbnail_count += 1
                          print(f"✓ Added thumbnail from content")
              
              # If no thumbnail found, use fallback
              if not img_url:
                  xml_parts.append(f'<media:thumbnail url="{fallback_thumbnail}"/>')
                  fallback_count += 1
                  print(f"✓ Added fallback thumbnail")
              
              # Ensure required fields
              if item.find('dc:creator', nsmap) is None:
                  xml_parts.append('<dc:creator>CableTV.com</dc:creator>')
              
              if item.find('pubDate') is None:
                  pubdate = datetime.now(timezone.utc).strftime('%a, %d %b %Y %H:%M:%S +0000')
                  xml_parts.append(f'<pubDate>{pubdate}</pubDate>')
              
              if item.find('description') is None and content_html:
                  text = re.sub(r'<[^>]+>', '', content_html)
                  text = text.strip()[:200] + '...'
                  text = text.replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;')
                  xml_parts.append(f'<description>{text}</description>')
              
              xml_parts.append('</item>')
          
          xml_parts.append('</channel>')
          xml_parts.append('</rss>')
          
          # Join all parts
          xml_string = ''.join(xml_parts)
          
          # Fix self-reference
          xml_string = xml_string.replace(
              'https://www.cabletv.com/feed',
              'https://ctv-clearlink.github.io/RSS-Feed/feed.xml'
          )
          
          # Write to file
          with open('feed.xml', 'w', encoding='utf-8') as f:
              f.write(xml_string)
          
          print(f"\n✓ Feed created with {cdata_count} CDATA sections")
          print(f"✓ Added {thumbnail_count} original + {fallback_count} fallback = {thumbnail_count + fallback_count}/{len(items)} total thumbnails")
          print(f"✓ Output size: {len(xml_string):,} bytes ({len(xml_string)/1024/1024:.2f} MB)")
          EOF
      
      - name: Verify feed
        run: |
          echo "Feed size:"
          ls -lh feed.xml
          echo ""
          echo "Thumbnail count:"
          grep -c "media:thumbnail" feed.xml || echo "0"
          echo ""
          echo "Item count:"
          grep -c "<item>" feed.xml
          
      - name: Check for changes
        id: changes
        run: |
          git diff --quiet feed.xml || echo "changed=true" >> $GITHUB_OUTPUT
      
      - name: Commit and push feed
        if: steps.changes.outputs.changed == 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add feed.xml
          git commit -m "Update RSS feed $(date '+%Y-%m-%d %H:%M:%S')"
          git pull --rebase origin main
          git push origin main
